name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn build

      - uses: UnlyEd/github-action-deploy-on-vercel@latest

        with:
          command: "vercel ./ --confirm --prod --token ${{ secrets.VERCEL_TOKEN }}"

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      BACKEND_API: ${{ secrets.BACKEND_API }}
